#intro to the print(colour) function and how to create a user generated story. 
print ("Welcome to your adventure simulator.")
print()
print("I am going to ask you a lot of questions and then generate a story using your prompts. Choose your own adventure and have fun!")
print()
name = input ("what is your name?")
print()
enemy = input ("who is your worst enemy?")
print()
superpower = input ("what is your superpower?")
print()
live = input("where do you live?")
print()
food = input ("what is your favourite food?")
print()
print("Hello", "\033[32m" ,name, "\033[0m", "Your ability to" , "\033[32m", superpower,"\033[0m", "will make sure you never have to look at", "\033[32m", enemy,  "\033[0m", "again. Go eat",  "\033[32m", food, "\033[0m", "as you walk down the streets of", "\033[32m", live, "\033[0m" "and use", "\033[32m", superpower, "\033[0m", "for good and not for evil!")
