print("what is your name?")
name = input("your name")
print("hello", name)
print("how old are you?")
age = input("your age")
print("so you're", age ,"years old")
print("what is your favourite food?")
food = input("your favourite food")
print("ooh,", food , "is delicious.")
print("who is your favourite artist?")
artist = input("your favourite artist")
print("wow", artist , "'s favourite artist is my favourite artist.. heh...")
print("where do you live?")
location = input("your location")
print("oh, i've heard", location , "is a nice place.")
print()
print("""wow, so your name is""", name ,)
print("""you are""", age , """years old""")
print("""your favourite food is""", food ,)
print("""your favourite artist is""", artist ,)
print("""and you live in""", location ,)
print("""that's prety sigma!""")
#this is an intro to the varName = input("prompt")
